### ISSUE TITLE
Diamond spreading calculation again

### ISSUE THREAD

**Issue by alexthepineapple** [RabidSheep55/MinionProfitsTracker#2]
Following on from https://github.com/RabidSheep55/MinionProfitsTracker/pull/1#issuecomment-619459939 (which discussion was accidentally misfiled with a the pull-request about filename-joining). I think the diamond bonus calculation is now (as of commit 2a63a69db3, Sun Apr 26 23:04:17 2020 +0200) correct for minions that drop only one kind of item, but not right for those that drop multiple items.

For minions with multiple items, the program is calculating something it calls avgYield, but it should be using the sum of the yields (over different item types) not the average to calculate this. For example with a fish minion, the true average yield per action is 0.5+0.25+0.12+0.04+0.03+0.03+0.03 = 1 item per action, but avgYield will end up equal to (0.5+0.25+0.12+0.04+0.03+0.03+0.03)/7 = 1/7. (Actually it uses very slightly different probabilities, but that doesn't make a big difference.)

**Comment by RabidSheep55** [comment]
You're correct once again... my apologies I didn't think about this enough, 
Thanks a lot for checking this!
Feel free to share any other suggestions/bugs haha

**Comment by alexthepineapple** [comment]
Hi again! You also need to reset the merchDiaBonus to 0 (as well as the diaBonus) in the case of no diamond spreading.
