### ISSUE TITLE
Buy price instead of sell price

### ISSUE THREAD

**Issue by demartinomarco** [RabidSheep55/MinionProfitsTracker#5]
Why are you doing your calculation with the buy price instead of the sell price?

**Comment by RabidSheep55** [comment]
Usually in sb people call the merchant sell price the cost at which you can buy the items from them, so I chose to call the price at which the merchant will buy from the player that. It goes both ways; the player is selling to the merchant, and the merchant is buying from the player - I don't think there's an issue here, please let me know if I've gotten something wrong!
